/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface GuessInterface extends utils.Interface {
  functions: {
    "attempt(uint8)": FunctionFragment;
    "close()": FunctionFragment;
    "erc20()": FunctionFragment;
    "guessRange()": FunctionFragment;
    "prizePool()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "attempt"
      | "close"
      | "erc20"
      | "guessRange"
      | "prizePool"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attempt",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "close", values?: undefined): string;
  encodeFunctionData(functionFragment: "erc20", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "guessRange",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "prizePool", values?: undefined): string;

  decodeFunctionResult(functionFragment: "attempt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "close", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "erc20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "guessRange", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "prizePool", data: BytesLike): Result;

  events: {
    "GuessResult(address,uint256,uint256,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GuessResult"): EventFragment;
}

export interface GuessResultEventObject {
  player: string;
  allowance: BigNumber;
  prize: BigNumber;
  guess: BigNumber;
  msg: string;
}
export type GuessResultEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string],
  GuessResultEventObject
>;

export type GuessResultEventFilter = TypedEventFilter<GuessResultEvent>;

export interface Guess extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GuessInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    attempt(
      guess: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    close(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    erc20(overrides?: CallOverrides): Promise<[string]>;

    guessRange(overrides?: CallOverrides): Promise<[number]>;

    prizePool(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  attempt(
    guess: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  close(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  erc20(overrides?: CallOverrides): Promise<string>;

  guessRange(overrides?: CallOverrides): Promise<number>;

  prizePool(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    attempt(
      guess: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    close(overrides?: CallOverrides): Promise<void>;

    erc20(overrides?: CallOverrides): Promise<string>;

    guessRange(overrides?: CallOverrides): Promise<number>;

    prizePool(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "GuessResult(address,uint256,uint256,uint256,string)"(
      player?: PromiseOrValue<string> | null,
      allowance?: null,
      prize?: null,
      guess?: null,
      msg?: null
    ): GuessResultEventFilter;
    GuessResult(
      player?: PromiseOrValue<string> | null,
      allowance?: null,
      prize?: null,
      guess?: null,
      msg?: null
    ): GuessResultEventFilter;
  };

  estimateGas: {
    attempt(
      guess: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    close(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    erc20(overrides?: CallOverrides): Promise<BigNumber>;

    guessRange(overrides?: CallOverrides): Promise<BigNumber>;

    prizePool(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    attempt(
      guess: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    close(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    erc20(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    guessRange(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    prizePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
