/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { Guess } from "./Guess";
export type { IERC20 } from "./IERC20";
