/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as guessSol from "./Guess.sol";
export type { guessSol };
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export type { Guess } from "./Guess.sol/Guess";
export { Guess__factory } from "./factories/Guess.sol/Guess__factory";
export type { IERC20 } from "./Guess.sol/IERC20";
export { IERC20__factory } from "./factories/Guess.sol/IERC20__factory";
